name: auto_updater
description: This plugin allows Flutter desktop apps to automatically update themselves (based on sparkle and winsparkle).
version: 0.1.7
homepage: https://github.com/leanflutter/auto_updater

platforms:
  macos:
  windows:

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  dependency_validator: ^3.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: AutoUpdaterPlugin
      windows:
        pluginClass: AutoUpdaterPlugin
